from typing import TypeAlias, overload

from pyyggdrasil.serialization import Table

from pytyr.formalism import planning as fp
from pytyr.planning import ground, lifted
from . import planning as runtime
from .formalism import planning as schema



RegisteredNative: TypeAlias = (
    fp.Object | fp.Variable | fp.StaticPredicate | fp.StaticPredicateBinding |
    fp.FluentPredicate | fp.FluentPredicateBinding | fp.DerivedPredicate | fp.DerivedPredicateBinding |
    fp.StaticFunction | fp.StaticFunctionBinding | fp.FluentFunction | fp.FluentFunctionBinding |
    fp.AuxiliaryFunction | fp.AuxiliaryFunctionBinding | fp.ActionBinding | fp.AxiomBinding |
    fp.Term | fp.StaticAtom | fp.StaticLiteral | fp.StaticGroundAtom |
    fp.StaticGroundLiteral | fp.FluentAtom | fp.FluentLiteral | fp.FluentGroundAtom |
    fp.FluentGroundLiteral | fp.DerivedAtom | fp.DerivedLiteral | fp.DerivedGroundAtom |
    fp.DerivedGroundLiteral | fp.StaticFunctionTerm | fp.StaticGroundFunctionTerm | fp.StaticGroundFunctionTermValue |
    fp.FluentFunctionTerm | fp.FluentGroundFunctionTerm | fp.FluentGroundFunctionTermValue | fp.AuxiliaryFunctionTerm |
    fp.AuxiliaryGroundFunctionTerm | fp.AuxiliaryGroundFunctionTermValue | fp.FluentFDRVariable | fp.FluentFDRFact |
    fp.FunctionExpression | fp.ArithmeticOperator | fp.BooleanOperator | fp.UnaryOperator |
    fp.MultiOperator | fp.BinaryArithmeticOperator | fp.BinaryBooleanOperator | fp.FluentNumericEffectOperator |
    fp.FluentNumericEffect | fp.AuxiliaryNumericEffectOperator | fp.AuxiliaryNumericEffect | fp.GroundFunctionExpression |
    fp.GroundArithmeticOperator | fp.GroundBooleanOperator | fp.GroundUnaryOperator | fp.GroundMultiOperator |
    fp.GroundBinaryArithmeticOperator | fp.GroundBinaryBooleanOperator | fp.FluentGroundNumericEffectOperator | fp.FluentGroundNumericEffect |
    fp.AuxiliaryGroundNumericEffectOperator | fp.AuxiliaryGroundNumericEffect | fp.Action | fp.Axiom |
    fp.ConditionalEffect | fp.ConjunctiveCondition | fp.ConjunctiveEffect | fp.GroundAction |
    fp.GroundAxiom | fp.GroundConditionalEffect | fp.GroundConjunctiveCondition | fp.GroundConjunctiveEffect |
    fp.Metric | fp.Domain | fp.LiftedTask | fp.GroundTask |
    ground.State | lifted.State | ground.Node | lifted.Node
)

class Dictionaries:
    def __init__(self) -> None: ...
    def register_table(self, native_type: type[RegisteredNative], name: str, prefix: str) -> None: ...
    def serialize(
        self,
        value: RegisteredNative | fp.PlanningDomain | fp.PlanningTask | fp.PlanningFDRTask
        | ground.LabeledNode | lifted.LabeledNode | ground.Plan | lifted.Plan
        | ground.Task | lifted.Task,
    ) -> str: ...
    @overload
    def table(self, native_type: type[fp.Object]) -> list[schema.Object]: ...
    @overload
    def table(self, native_type: type[fp.Variable]) -> list[schema.Variable]: ...
    @overload
    def table(self, native_type: type[fp.StaticPredicate]) -> list[schema.StaticPredicate]: ...
    @overload
    def table(self, native_type: type[fp.StaticPredicateBinding]) -> list[schema.StaticPredicateBinding]: ...
    @overload
    def table(self, native_type: type[fp.FluentPredicate]) -> list[schema.FluentPredicate]: ...
    @overload
    def table(self, native_type: type[fp.FluentPredicateBinding]) -> list[schema.FluentPredicateBinding]: ...
    @overload
    def table(self, native_type: type[fp.DerivedPredicate]) -> list[schema.DerivedPredicate]: ...
    @overload
    def table(self, native_type: type[fp.DerivedPredicateBinding]) -> list[schema.DerivedPredicateBinding]: ...
    @overload
    def table(self, native_type: type[fp.StaticFunction]) -> list[schema.StaticFunction]: ...
    @overload
    def table(self, native_type: type[fp.StaticFunctionBinding]) -> list[schema.StaticFunctionBinding]: ...
    @overload
    def table(self, native_type: type[fp.FluentFunction]) -> list[schema.FluentFunction]: ...
    @overload
    def table(self, native_type: type[fp.FluentFunctionBinding]) -> list[schema.FluentFunctionBinding]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryFunction]) -> list[schema.AuxiliaryFunction]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryFunctionBinding]) -> list[schema.AuxiliaryFunctionBinding]: ...
    @overload
    def table(self, native_type: type[fp.ActionBinding]) -> list[schema.ActionBinding]: ...
    @overload
    def table(self, native_type: type[fp.AxiomBinding]) -> list[schema.AxiomBinding]: ...
    @overload
    def table(self, native_type: type[fp.Term]) -> list[schema.Term]: ...
    @overload
    def table(self, native_type: type[fp.StaticAtom]) -> list[schema.StaticAtom]: ...
    @overload
    def table(self, native_type: type[fp.StaticLiteral]) -> list[schema.StaticLiteral]: ...
    @overload
    def table(self, native_type: type[fp.StaticGroundAtom]) -> list[schema.StaticGroundAtom]: ...
    @overload
    def table(self, native_type: type[fp.StaticGroundLiteral]) -> list[schema.StaticGroundLiteral]: ...
    @overload
    def table(self, native_type: type[fp.FluentAtom]) -> list[schema.FluentAtom]: ...
    @overload
    def table(self, native_type: type[fp.FluentLiteral]) -> list[schema.FluentLiteral]: ...
    @overload
    def table(self, native_type: type[fp.FluentGroundAtom]) -> list[schema.FluentGroundAtom]: ...
    @overload
    def table(self, native_type: type[fp.FluentGroundLiteral]) -> list[schema.FluentGroundLiteral]: ...
    @overload
    def table(self, native_type: type[fp.DerivedAtom]) -> list[schema.DerivedAtom]: ...
    @overload
    def table(self, native_type: type[fp.DerivedLiteral]) -> list[schema.DerivedLiteral]: ...
    @overload
    def table(self, native_type: type[fp.DerivedGroundAtom]) -> list[schema.DerivedGroundAtom]: ...
    @overload
    def table(self, native_type: type[fp.DerivedGroundLiteral]) -> list[schema.DerivedGroundLiteral]: ...
    @overload
    def table(self, native_type: type[fp.StaticFunctionTerm]) -> list[schema.StaticFunctionTerm]: ...
    @overload
    def table(self, native_type: type[fp.StaticGroundFunctionTerm]) -> list[schema.StaticGroundFunctionTerm]: ...
    @overload
    def table(self, native_type: type[fp.StaticGroundFunctionTermValue]) -> list[schema.StaticGroundFunctionTermValue]: ...
    @overload
    def table(self, native_type: type[fp.FluentFunctionTerm]) -> list[schema.FluentFunctionTerm]: ...
    @overload
    def table(self, native_type: type[fp.FluentGroundFunctionTerm]) -> list[schema.FluentGroundFunctionTerm]: ...
    @overload
    def table(self, native_type: type[fp.FluentGroundFunctionTermValue]) -> list[schema.FluentGroundFunctionTermValue]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryFunctionTerm]) -> list[schema.AuxiliaryFunctionTerm]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryGroundFunctionTerm]) -> list[schema.AuxiliaryGroundFunctionTerm]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryGroundFunctionTermValue]) -> list[schema.AuxiliaryGroundFunctionTermValue]: ...
    @overload
    def table(self, native_type: type[fp.FluentFDRVariable]) -> list[schema.FluentFDRVariable]: ...
    @overload
    def table(self, native_type: type[fp.FluentFDRFact]) -> list[schema.FluentFDRFact]: ...
    @overload
    def table(self, native_type: type[fp.FunctionExpression]) -> list[schema.FunctionExpression]: ...
    @overload
    def table(self, native_type: type[fp.ArithmeticOperator]) -> list[schema.ArithmeticOperator]: ...
    @overload
    def table(self, native_type: type[fp.BooleanOperator]) -> list[schema.BooleanOperator]: ...
    @overload
    def table(self, native_type: type[fp.UnaryOperator]) -> list[schema.UnaryOperator]: ...
    @overload
    def table(self, native_type: type[fp.MultiOperator]) -> list[schema.MultiOperator]: ...
    @overload
    def table(self, native_type: type[fp.BinaryArithmeticOperator]) -> list[schema.BinaryArithmeticOperator]: ...
    @overload
    def table(self, native_type: type[fp.BinaryBooleanOperator]) -> list[schema.BinaryBooleanOperator]: ...
    @overload
    def table(self, native_type: type[fp.FluentNumericEffectOperator]) -> list[schema.FluentNumericEffectOperator]: ...
    @overload
    def table(self, native_type: type[fp.FluentNumericEffect]) -> list[schema.FluentNumericEffect]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryNumericEffectOperator]) -> list[schema.AuxiliaryNumericEffectOperator]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryNumericEffect]) -> list[schema.AuxiliaryNumericEffect]: ...
    @overload
    def table(self, native_type: type[fp.GroundFunctionExpression]) -> list[schema.GroundFunctionExpression]: ...
    @overload
    def table(self, native_type: type[fp.GroundArithmeticOperator]) -> list[schema.GroundArithmeticOperator]: ...
    @overload
    def table(self, native_type: type[fp.GroundBooleanOperator]) -> list[schema.GroundBooleanOperator]: ...
    @overload
    def table(self, native_type: type[fp.GroundUnaryOperator]) -> list[schema.GroundUnaryOperator]: ...
    @overload
    def table(self, native_type: type[fp.GroundMultiOperator]) -> list[schema.GroundMultiOperator]: ...
    @overload
    def table(self, native_type: type[fp.GroundBinaryArithmeticOperator]) -> list[schema.GroundBinaryArithmeticOperator]: ...
    @overload
    def table(self, native_type: type[fp.GroundBinaryBooleanOperator]) -> list[schema.GroundBinaryBooleanOperator]: ...
    @overload
    def table(self, native_type: type[fp.FluentGroundNumericEffectOperator]) -> list[schema.FluentGroundNumericEffectOperator]: ...
    @overload
    def table(self, native_type: type[fp.FluentGroundNumericEffect]) -> list[schema.FluentGroundNumericEffect]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryGroundNumericEffectOperator]) -> list[schema.AuxiliaryGroundNumericEffectOperator]: ...
    @overload
    def table(self, native_type: type[fp.AuxiliaryGroundNumericEffect]) -> list[schema.AuxiliaryGroundNumericEffect]: ...
    @overload
    def table(self, native_type: type[fp.Action]) -> list[schema.Action]: ...
    @overload
    def table(self, native_type: type[fp.Axiom]) -> list[schema.Axiom]: ...
    @overload
    def table(self, native_type: type[fp.ConditionalEffect]) -> list[schema.ConditionalEffect]: ...
    @overload
    def table(self, native_type: type[fp.ConjunctiveCondition]) -> list[schema.ConjunctiveCondition]: ...
    @overload
    def table(self, native_type: type[fp.ConjunctiveEffect]) -> list[schema.ConjunctiveEffect]: ...
    @overload
    def table(self, native_type: type[fp.GroundAction]) -> list[schema.GroundAction]: ...
    @overload
    def table(self, native_type: type[fp.GroundAxiom]) -> list[schema.GroundAxiom]: ...
    @overload
    def table(self, native_type: type[fp.GroundConditionalEffect]) -> list[schema.GroundConditionalEffect]: ...
    @overload
    def table(self, native_type: type[fp.GroundConjunctiveCondition]) -> list[schema.GroundConjunctiveCondition]: ...
    @overload
    def table(self, native_type: type[fp.GroundConjunctiveEffect]) -> list[schema.GroundConjunctiveEffect]: ...
    @overload
    def table(self, native_type: type[fp.Metric]) -> list[schema.Metric]: ...
    @overload
    def table(self, native_type: type[fp.Domain]) -> list[schema.Domain]: ...
    @overload
    def table(self, native_type: type[fp.LiftedTask]) -> list[schema.LiftedTask]: ...
    @overload
    def table(self, native_type: type[fp.GroundTask]) -> list[schema.GroundTask]: ...
    @overload
    def table(self, native_type: type[ground.State] | type[lifted.State]) -> list[runtime.State]: ...
    @overload
    def table(self, native_type: type[ground.Node] | type[lifted.Node]) -> list[runtime.Node]: ...
    def tables(self) -> dict[str, Table]: ...
