# Import all classes for better IDE support

from ..._pytyr.formalism.planning import (
    MutableStaticAtom,
    MutableFluentAtom,
    MutableDerivedAtom,
    MutableStaticLiteral,
    MutableFluentLiteral,
    MutableDerivedLiteral,
    MutableConjunctiveCondition,
    MutableConjunctiveEffect,
    MutableConditionalEffect,
    MutableAction,
)

from ..._pytyr.formalism.planning import (
    Invariant,
    synthesize_invariants,
    ObjectSubstitution,
    TermSubstitution,
    InvariantMatchData,
    InvariantQueryWorkspace,
    InvariantQueryResult,
    InvariantQueryResultMatch,
    InvariantMatcher,
)

from ..._pytyr.formalism.planning import (
    VariableDomain,
    AxiomDomain,
    ConjunctiveConditionDomain,
    ConjunctiveEffectDomain,
    ConditionalEffectDomain,
    ActionDomain,
    TaskVariableDomains,
)

from ..._pytyr.formalism.planning import (
    # Core symbols
    BooleanOperatorKind,
    ArithmeticOperatorKind,
    NumericEffectOperatorKind,
    RowIndex,
    Object,
    ObjectIndex,
    ObjectData,
    ActionBindingData,
    AxiomBindingData,
    Variable,
    VariableIndex,
    VariableData,
    ParameterIndex,
    Term,
    TermData,

    StaticPredicateBinding,
    StaticPredicateBindingIndex,
    StaticPredicateBindingData,
    FluentPredicateBinding,
    FluentPredicateBindingIndex,
    FluentPredicateBindingData,
    DerivedPredicateBinding,
    DerivedPredicateBindingIndex,
    DerivedPredicateBindingData,
    StaticFunctionBinding,
    StaticFunctionBindingIndex,
    StaticFunctionBindingData,
    FluentFunctionBinding,
    FluentFunctionBindingIndex,
    FluentFunctionBindingData,
    AuxiliaryFunctionBinding,
    AuxiliaryFunctionBindingIndex,
    AuxiliaryFunctionBindingData,
    ActionBinding,
    ActionBindingIndex,
    ActionBindingData,
    AxiomBinding,
    AxiomBindingIndex,
    AxiomBindingData,

    # Predicates
    StaticPredicate,
    StaticPredicateIndex,
    StaticPredicateData,
    FluentPredicate,
    FluentPredicateIndex,
    FluentPredicateData,
    DerivedPredicate,
    DerivedPredicateIndex,
    DerivedPredicateData,

    # Atoms
    StaticAtom,
    StaticAtomIndex,
    StaticAtomData,
    FluentAtom,
    FluentAtomIndex,
    FluentAtomData,
    DerivedAtom,
    DerivedAtomIndex,
    DerivedAtomData,
    StaticGroundAtom,
    StaticGroundAtomIndex,
    StaticGroundAtomData,
    FluentGroundAtom,
    FluentGroundAtomIndex,
    FluentGroundAtomData,
    DerivedGroundAtom,
    DerivedGroundAtomIndex,
    DerivedGroundAtomData,

    # Literals
    StaticLiteral,
    StaticLiteralIndex,
    StaticLiteralData,
    FluentLiteral,
    FluentLiteralIndex,
    FluentLiteralData,
    DerivedLiteral,
    DerivedLiteralIndex,
    DerivedLiteralData,
    StaticGroundLiteral,
    StaticGroundLiteralIndex,
    StaticGroundLiteralData,
    FluentGroundLiteral,
    FluentGroundLiteralIndex,
    FluentGroundLiteralData,
    DerivedGroundLiteral,
    DerivedGroundLiteralIndex,
    DerivedGroundLiteralData,
    FluentFDRVariable,
    FluentFDRVariableIndex,
    FluentFDRVariableData,
    FDRValue,
    FluentFDRFact,
    FluentFDRFactData,

    # Functions
    StaticFunction,
    StaticFunctionIndex,
    StaticFunctionData,
    FluentFunction,
    FluentFunctionIndex,
    FluentFunctionData,
    AuxiliaryFunction,
    AuxiliaryFunctionIndex,
    AuxiliaryFunctionData,

    # FunctionTerms
    StaticFunctionTerm,
    StaticFunctionTermIndex,
    StaticFunctionTermData,
    FluentFunctionTerm,
    FluentFunctionTermIndex,
    FluentFunctionTermData,
    AuxiliaryFunctionTerm,
    AuxiliaryFunctionTermIndex,
    AuxiliaryFunctionTermData,
    StaticGroundFunctionTerm,
    StaticGroundFunctionTermIndex,
    StaticGroundFunctionTermData,
    FluentGroundFunctionTerm,
    FluentGroundFunctionTermIndex,
    FluentGroundFunctionTermData,
    AuxiliaryGroundFunctionTerm,
    AuxiliaryGroundFunctionTermIndex,
    AuxiliaryGroundFunctionTermData,

    # FunctionTermValues
    StaticGroundFunctionTermValue,
    StaticGroundFunctionTermValueIndex,
    StaticGroundFunctionTermValueData,
    FluentGroundFunctionTermValue,
    FluentGroundFunctionTermValueIndex,
    FluentGroundFunctionTermValueData,
    AuxiliaryGroundFunctionTermValue,
    AuxiliaryGroundFunctionTermValueIndex,
    AuxiliaryGroundFunctionTermValueData,

    # Operators
    UnaryOperator,
    UnaryOperatorIndex,
    UnaryOperatorData,
    BinaryArithmeticOperator,
    BinaryArithmeticOperatorIndex,
    BinaryArithmeticOperatorData,
    BinaryBooleanOperator,
    BinaryBooleanOperatorIndex,
    BinaryBooleanOperatorData,
    MultiOperator,
    MultiOperatorIndex,
    MultiOperatorData,
    ArithmeticOperator,
    ArithmeticOperatorData,
    BooleanOperator,
    BooleanOperatorData,
    FunctionExpression,
    FunctionExpressionData,

    # Condition
    ConjunctiveCondition,
    ConjunctiveConditionIndex,
    ConjunctiveConditionData,

    # Effects
    FluentNumericEffect,
    FluentNumericEffectIndex,
    FluentNumericEffectData,
    AuxiliaryNumericEffect,
    AuxiliaryNumericEffectIndex,
    AuxiliaryNumericEffectData,
    FluentNumericEffectOperator,
    FluentNumericEffectOperatorData,
    AuxiliaryNumericEffectOperator,
    AuxiliaryNumericEffectOperatorData,
    ConjunctiveEffect,
    ConjunctiveEffectIndex,
    ConjunctiveEffectData,
    ConditionalEffect,
    ConditionalEffectIndex,
    ConditionalEffectData,

    # Action
    Action,
    ActionIndex,
    ActionData,

    # Axiom
    Axiom,
    AxiomIndex,
    AxiomData,

    # Ground Operators
    GroundUnaryOperator,
    GroundUnaryOperatorIndex,
    GroundUnaryOperatorData,
    GroundBinaryArithmeticOperator,
    GroundBinaryArithmeticOperatorIndex,
    GroundBinaryArithmeticOperatorData,
    GroundBinaryBooleanOperator,
    GroundBinaryBooleanOperatorIndex,
    GroundBinaryBooleanOperatorData,
    GroundMultiOperator,
    GroundMultiOperatorIndex,
    GroundMultiOperatorData,
    GroundArithmeticOperator,
    GroundArithmeticOperatorData,
    GroundBooleanOperator,
    GroundBooleanOperatorData,
    GroundFunctionExpression,
    GroundFunctionExpressionData,

    # GroundCondition
    GroundConjunctiveCondition,
    GroundConjunctiveConditionIndex,
    GroundConjunctiveConditionData,

    # Ground NumericEffects
    FluentGroundNumericEffect,
    FluentGroundNumericEffectIndex,
    FluentGroundNumericEffectData,
    AuxiliaryGroundNumericEffect,
    AuxiliaryGroundNumericEffectIndex,
    AuxiliaryGroundNumericEffectData,
    FluentGroundNumericEffectOperator,
    FluentGroundNumericEffectOperatorData,
    AuxiliaryGroundNumericEffectOperator,
    AuxiliaryGroundNumericEffectOperatorData,
    GroundConjunctiveEffect,
    GroundConjunctiveEffectIndex,
    GroundConjunctiveEffectData,
    GroundConditionalEffect,
    GroundConditionalEffectIndex,
    GroundConditionalEffectData,

    # GroundAction
    GroundAction,
    GroundActionIndex,
    GroundActionData,

    # GroundAxiom
    GroundAxiom,
    GroundAxiomIndex,
    GroundAxiomData,

    # Tasks
    OptimizationDirection,
    Metric,
    MetricIndex,
    MetricData,
    Domain,
    DomainIndex,
    DomainData,
    LiftedTask,
    LiftedTaskIndex,
    LiftedTaskData,
    GroundTask,
    GroundTaskIndex,
    GroundTaskData,
    PlanningDomain,
    PlanningTask,
    PlanningFDRTask,

    # Parser
    Parser,

    # Repository
    RepositoryFactory,
    Repository,

    # FDRContext
    FDRContext,
)
