class Keys:
    SCHEMA_VERSION = "schema_version"
    TOOL = "tool"
    STATUS = "status"
    TASK = "task"
    CONTEXT = "context"
    BACKEND = "backend"
    INDEX = "index"
    NAME = "name"
    SOLVED = "solved"
    PLAN_COST = "plan_cost"
    PLAN_LENGTH = "plan_length"
    DOMAIN_PATH = "domain_path"
    PLAN_PATH = "plan_path"
    TASK_PATH = "task_path"
